### PR TITLE
Preparation to serve site

### PR DESCRIPTION
**Pull request by jvwong**
A) `build` script now triggers `build:data` which fetches article data 
B) Symlink from `./dist` to `./src/dashboard` etc - not sure if this is what you were looking for?

Refs #25

### CODE REVIEW

**Comment by maxkfranz** [comment]
Let's give it a try

**Comment by maxkfranz** [comment]
It looks like there's an error in the script:

```
2022-11-08T22:35:49.741348Z	Cloning repository...
2022-11-08T22:35:53.596815Z	From https://github.com/PathwayCommons/hyper-recent
2022-11-08T22:35:53.597422Z	 * branch            e78e666665397f2d1e3b0d0b7ed17ad098c15655 -> FETCH_HEAD
2022-11-08T22:35:53.597597Z	
2022-11-08T22:35:54.129442Z	HEAD is now at e78e666 Merge pull request #26 from PathwayCommons/iss25_static-site
2022-11-08T22:35:54.130011Z	
2022-11-08T22:35:54.27415Z	
2022-11-08T22:35:54.302514Z	Success: Finished cloning repository files
2022-11-08T22:35:55.129815Z	Installing dependencies
2022-11-08T22:35:55.142616Z	Python version set to 2.7
2022-11-08T22:35:57.013007Z	Attempting node version 'v16.16.0' from .nvmrc
2022-11-08T22:35:58.509364Z	Downloading and installing node v16.16.0...
2022-11-08T22:35:58.936302Z	Downloading https://nodejs.org/dist/v16.16.0/node-v16.16.0-linux-x64.tar.xz...
2022-11-08T22:35:59.484539Z	Computing checksum with sha256sum
2022-11-08T22:35:59.614153Z	Checksums matched!
2022-11-08T22:36:03.878367Z	Now using node v16.16.0 (npm v8.11.0)
2022-11-08T22:36:04.267912Z	Started restoring cached build plugins
2022-11-08T22:36:04.281072Z	Finished restoring cached build plugins
2022-11-08T22:36:04.767112Z	Attempting ruby version 2.7.1, read from environment
2022-11-08T22:36:08.236195Z	Using ruby version 2.7.1
2022-11-08T22:36:08.586182Z	Using PHP version 5.6
2022-11-08T22:36:08.753857Z	5.2 is already installed.
2022-11-08T22:36:08.781Z	Using Swift version 5.2
2022-11-08T22:36:08.782Z	Started restoring cached node modules
2022-11-08T22:36:08.797503Z	Finished restoring cached node modules
2022-11-08T22:36:09.297927Z	Installing NPM modules using NPM version 8.11.0
2022-11-08T22:36:09.706224Z	npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
2022-11-08T22:36:09.706637Z	npm WARN config location in the cache, and they are managed by
2022-11-08T22:36:09.706965Z	npm WARN config     [`cacache`](http://npm.im/cacache).
2022-11-08T22:36:10.105795Z	npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
2022-11-08T22:36:10.106143Z	npm WARN config location in the cache, and they are managed by
2022-11-08T22:36:10.106383Z	npm WARN config     [`cacache`](http://npm.im/cacache).
2022-11-08T22:36:18.774088Z	
2022-11-08T22:36:18.774443Z	added 443 packages, and audited 444 packages in 9s
2022-11-08T22:36:18.774613Z	
2022-11-08T22:36:18.774768Z	88 packages are looking for funding
2022-11-08T22:36:18.775092Z	  run `npm fund` for details
2022-11-08T22:36:18.778653Z	
2022-11-08T22:36:18.778887Z	1 moderate severity vulnerability
2022-11-08T22:36:18.779027Z	
2022-11-08T22:36:18.779153Z	To address all issues, run:
2022-11-08T22:36:18.779307Z	  npm audit fix
2022-11-08T22:36:18.779447Z	
2022-11-08T22:36:18.77956Z	Run `npm audit` for details.
2022-11-08T22:36:18.792903Z	NPM modules installed
2022-11-08T22:36:19.357352Z	npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
2022-11-08T22:36:19.357794Z	npm WARN config location in the cache, and they are managed by
2022-11-08T22:36:19.358075Z	npm WARN config     [`cacache`](http://npm.im/cacache).
2022-11-08T22:36:19.376556Z	Installing Hugo 0.54.0
2022-11-08T22:36:20.101622Z	Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
2022-11-08T22:36:20.105912Z	Started restoring cached go cache
2022-11-08T22:36:20.124716Z	Finished restoring cached go cache
2022-11-08T22:36:20.265424Z	go version go1.14.4 linux/amd64
2022-11-08T22:36:20.280059Z	go version go1.14.4 linux/amd64
2022-11-08T22:36:20.282846Z	Installing missing commands
2022-11-08T22:36:20.283121Z	Verify run directory
2022-11-08T22:36:20.283253Z	Executing user command: npm run build
2022-11-08T22:36:20.755339Z	npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
2022-11-08T22:36:20.755675Z	npm WARN config location in the cache, and they are managed by
2022-11-08T22:36:20.755835Z	npm WARN config     [`cacache`](http://npm.im/cacache).
2022-11-08T22:36:20.772019Z	
2022-11-08T22:36:20.772277Z	> hyper-recent@1.0.0 build
2022-11-08T22:36:20.772432Z	> run-s build:data build:css build:js
2022-11-08T22:36:20.772556Z	
2022-11-08T22:36:21.377153Z	npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
2022-11-08T22:36:21.377517Z	npm WARN config location in the cache, and they are managed by
2022-11-08T22:36:21.377673Z	npm WARN config     [`cacache`](http://npm.im/cacache).
2022-11-08T22:36:21.392274Z	
2022-11-08T22:36:21.392546Z	> hyper-recent@1.0.0 build:data
2022-11-08T22:36:21.392685Z	> cd ./scripts && ./search.sh && ./recommendations.sh
2022-11-08T22:36:21.392802Z	
2022-11-08T22:36:21.424874Z	date: invalid option -- 'v'
2022-11-08T22:36:21.425318Z	Try 'date --help' for more information.
2022-11-08T22:36:21.43242Z	Fetching from biorxiv between  and 2022-11-08
2022-11-08T22:36:21.621304Z	error: missing required argument 'endDate'
2022-11-08T22:36:21.643309Z	numPapersRawBiorxiv: 
2022-11-08T22:36:21.643641Z	Fetching from medrxiv between  and 2022-11-08
2022-11-08T22:36:21.818327Z	error: missing required argument 'endDate'
2022-11-08T22:36:21.837753Z	numPapersRawMedrxiv: 
2022-11-08T22:36:21.838979Z	Combining results...
2022-11-08T22:36:21.846275Z	jq: error: Could not open file ../example-data/2022-11-08_*.json: No such file or directory
2022-11-08T22:36:21.855159Z	jq - commandline JSON processor [version 1.5-1-a5b5cbe]
2022-11-08T22:36:21.855683Z	Usage: jq [options] <jq filter> [file...]
2022-11-08T22:36:21.856898Z	
2022-11-08T22:36:21.85741Z		jq is a tool for processing JSON inputs, applying the
2022-11-08T22:36:21.857649Z		given filter to its JSON text inputs and producing the
2022-11-08T22:36:21.857883Z		filter's results as JSON on standard output.
2022-11-08T22:36:21.858124Z		The simplest filter is ., which is the identity filter,
2022-11-08T22:36:21.858363Z		copying jq's input to its output unmodified (except for
2022-11-08T22:36:21.858614Z		formatting).
2022-11-08T22:36:21.858821Z		For more advanced filters see the jq(1) manpage ("man jq")
2022-11-08T22:36:21.859017Z		and/or https://stedolan.github.io/jq
2022-11-08T22:36:21.860077Z	
2022-11-08T22:36:21.860427Z		Some of the options include:
2022-11-08T22:36:21.860662Z		 -c		compact instead of pretty-printed output;
2022-11-08T22:36:21.860846Z		 -n		use `null` as the single input value;
2022-11-08T22:36:21.861005Z		 -e		set the exit status code based on the output;
2022-11-08T22:36:21.861166Z		 -s		read (slurp) all inputs into an array; apply filter to it;
2022-11-08T22:36:21.861285Z		 -r		output raw strings, not JSON texts;
2022-11-08T22:36:21.861495Z		 -R		read raw strings, not JSON texts;
2022-11-08T22:36:21.861671Z		 -C		colorize JSON;
2022-11-08T22:36:21.86184Z		 -M		monochrome (don't colorize JSON);
2022-11-08T22:36:21.862023Z		 -S		sort keys of objects on output;
2022-11-08T22:36:21.862152Z		 --tab	use tabs for indentation;
2022-11-08T22:36:21.862262Z		 --arg a v	set variable $a to value <v>;
2022-11-08T22:36:21.86238Z		 --argjson a v	set variable $a to JSON value <v>;
2022-11-08T22:36:21.862507Z		 --slurpfile a f	set variable $a to an array of JSON texts read from <f>;
2022-11-08T22:36:21.862635Z		See the manpage for more options.
2022-11-08T22:36:21.862754Z	Searching for alzheimers-disease
2022-11-08T22:36:22.03935Z	undefined:1
2022-11-08T22:36:22.039676Z	
2022-11-08T22:36:22.039834Z	
2022-11-08T22:36:22.039953Z	SyntaxError: Unexpected end of JSON input
2022-11-08T22:36:22.040075Z	    at JSON.parse (<anonymous>)
2022-11-08T22:36:22.040199Z	    at getInput (file:///opt/buildhome/repo/src/cli.js:67:17)
2022-11-08T22:36:22.040324Z	    at async Command.search (file:///opt/buildhome/repo/src/cli.js:23:20)
2022-11-08T22:36:22.040478Z	    at async Command.parseAsync (/opt/buildhome/repo/node_modules/commander/lib/command.js:917:5)
2022-11-08T22:36:22.040598Z	    at async main (file:///opt/buildhome/repo/src/cli.js:103:3)
2022-11-08T22:36:22.058635Z	Found  hits
2022-11-08T22:36:22.080143Z	jq - commandline JSON processor [version 1.5-1-a5b5cbe]
2022-11-08T22:36:22.080485Z	Usage: jq [options] <jq filter> [file...]
2022-11-08T22:36:22.080641Z	
2022-11-08T22:36:22.080773Z		jq is a tool for processing JSON inputs, applying the
2022-11-08T22:36:22.080908Z		given filter to its JSON text inputs and producing the
2022-11-08T22:36:22.08103Z		filter's results as JSON on standard output.
2022-11-08T22:36:22.081139Z		The simplest filter is ., which is the identity filter,
2022-11-08T22:36:22.081247Z		copying jq's input to its output unmodified (except for
2022-11-08T22:36:22.08137Z		formatting).
2022-11-08T22:36:22.081692Z		For more advanced filters see the jq(1) manpage ("man jq")
2022-11-08T22:36:22.081834Z		and/or https://stedolan.github.io/jq
2022-11-08T22:36:22.081948Z	
2022-11-08T22:36:22.082055Z		Some of the options include:
2022-11-08T22:36:22.082162Z		 -c		compact instead of pretty-printed output;
2022-11-08T22:36:22.082273Z		 -n		use `null` as the single input value;
2022-11-08T22:36:22.082404Z		 -e		set the exit status code based on the output;
2022-11-08T22:36:22.082528Z		 -s		read (slurp) all inputs into an array; apply filter to it;
2022-11-08T22:36:22.08264Z		 -r		output raw strings, not JSON texts;
2022-11-08T22:36:22.082768Z		 -R		read raw strings, not JSON texts;
2022-11-08T22:36:22.082885Z		 -C		colorize JSON;
2022-11-08T22:36:22.082996Z		 -M		monochrome (don't colorize JSON);
2022-11-08T22:36:22.083102Z		 -S		sort keys of objects on output;
2022-11-08T22:36:22.083207Z		 --tab	use tabs for indentation;
2022-11-08T22:36:22.083369Z		 --arg a v	set variable $a to value <v>;
2022-11-08T22:36:22.083507Z		 --argjson a v	set variable $a to JSON value <v>;
2022-11-08T22:36:22.083628Z		 --slurpfile a f	set variable $a to an array of JSON texts read from <f>;
2022-11-08T22:36:22.083812Z		See the manpage for more options.
2022-11-08T22:36:22.093703Z	ERROR: "build:data" exited with 2.
2022-11-08T22:36:22.112113Z	Failed: build command exited with code: 1
2022-11-08T22:36:23.061073Z	Failed: an internal error occurred
```

The initial problem is this:

```
2022-11-08T22:36:21.424874Z	date: invalid option -- 'v'
2022-11-08T22:36:21.425318Z	Try 'date --help' for more information.
2022-11-08T22:36:21.43242Z	Fetching from biorxiv between  and 2022-11-08
2022-11-08T22:36:21.621304Z	error: missing required argument 'endDate'
```

`date` is different on Mac than it is on Linux, so either a more general command/options should be used or we could just hardcode the dates for now.

**Comment by maxkfranz** [comment]
The date is OK, but the data processing is failing:

```
2022-11-08T23:10:55.652744Z	Cloning repository...
2022-11-08T23:10:58.764597Z	From https://github.com/PathwayCommons/hyper-recent
2022-11-08T23:10:58.765089Z	 * branch            a455c9d6997caf9afb9447eb75327b0768bb026b -> FETCH_HEAD
2022-11-08T23:10:58.765224Z	
2022-11-08T23:10:59.223999Z	HEAD is now at a455c9d OS-agnostic dates #26
2022-11-08T23:10:59.224421Z	
2022-11-08T23:10:59.340196Z	
2022-11-08T23:10:59.364775Z	Success: Finished cloning repository files
2022-11-08T23:11:00.130095Z	Installing dependencies
2022-11-08T23:11:00.139041Z	Python version set to 2.7
2022-11-08T23:11:01.659244Z	Attempting node version 'v16.16.0' from .nvmrc
2022-11-08T23:11:02.844653Z	Downloading and installing node v16.16.0...
2022-11-08T23:11:03.20416Z	Downloading https://nodejs.org/dist/v16.16.0/node-v16.16.0-linux-x64.tar.xz...
2022-11-08T23:11:03.619321Z	Computing checksum with sha256sum
2022-11-08T23:11:03.738395Z	Checksums matched!
2022-11-08T23:11:07.391256Z	Now using node v16.16.0 (npm v8.11.0)
2022-11-08T23:11:07.730741Z	Started restoring cached build plugins
2022-11-08T23:11:07.741565Z	Finished restoring cached build plugins
2022-11-08T23:11:08.149397Z	Attempting ruby version 2.7.1, read from environment
2022-11-08T23:11:11.01931Z	Using ruby version 2.7.1
2022-11-08T23:11:11.318024Z	Using PHP version 5.6
2022-11-08T23:11:11.446839Z	5.2 is already installed.
2022-11-08T23:11:11.472923Z	Using Swift version 5.2
2022-11-08T23:11:11.474051Z	Started restoring cached node modules
2022-11-08T23:11:11.487159Z	Finished restoring cached node modules
2022-11-08T23:11:11.892673Z	Installing NPM modules using NPM version 8.11.0
2022-11-08T23:11:12.220589Z	npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
2022-11-08T23:11:12.220905Z	npm WARN config location in the cache, and they are managed by
2022-11-08T23:11:12.221072Z	npm WARN config     [`cacache`](http://npm.im/cacache).
2022-11-08T23:11:12.546342Z	npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
2022-11-08T23:11:12.546614Z	npm WARN config location in the cache, and they are managed by
2022-11-08T23:11:12.546733Z	npm WARN config     [`cacache`](http://npm.im/cacache).
2022-11-08T23:11:23.98791Z	
2022-11-08T23:11:23.988205Z	added 444 packages, and audited 445 packages in 11s
2022-11-08T23:11:23.988326Z	
2022-11-08T23:11:23.988419Z	89 packages are looking for funding
2022-11-08T23:11:23.98851Z	  run `npm fund` for details
2022-11-08T23:11:23.991936Z	
2022-11-08T23:11:23.992168Z	1 moderate severity vulnerability
2022-11-08T23:11:23.992303Z	
2022-11-08T23:11:23.992474Z	To address all issues, run:
2022-11-08T23:11:23.992628Z	  npm audit fix
2022-11-08T23:11:23.992738Z	
2022-11-08T23:11:23.992862Z	Run `npm audit` for details.
2022-11-08T23:11:24.007821Z	NPM modules installed
2022-11-08T23:11:24.449177Z	npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
2022-11-08T23:11:24.449436Z	npm WARN config location in the cache, and they are managed by
2022-11-08T23:11:24.449555Z	npm WARN config     [`cacache`](http://npm.im/cacache).
2022-11-08T23:11:24.465438Z	Installing Hugo 0.54.0
2022-11-08T23:11:25.105439Z	Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
2022-11-08T23:11:25.108959Z	Started restoring cached go cache
2022-11-08T23:11:25.124036Z	Finished restoring cached go cache
2022-11-08T23:11:25.236643Z	go version go1.14.4 linux/amd64
2022-11-08T23:11:25.248289Z	go version go1.14.4 linux/amd64
2022-11-08T23:11:25.250692Z	Installing missing commands
2022-11-08T23:11:25.250895Z	Verify run directory
2022-11-08T23:11:25.25101Z	Executing user command: npm run build
2022-11-08T23:11:25.630393Z	npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
2022-11-08T23:11:25.630752Z	npm WARN config location in the cache, and they are managed by
2022-11-08T23:11:25.630873Z	npm WARN config     [`cacache`](http://npm.im/cacache).
2022-11-08T23:11:25.644604Z	
2022-11-08T23:11:25.644819Z	> hyper-recent@1.0.0 build
2022-11-08T23:11:25.644922Z	> run-s build:data build:css build:js
2022-11-08T23:11:25.645013Z	
2022-11-08T23:11:26.142219Z	npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
2022-11-08T23:11:26.142505Z	npm WARN config location in the cache, and they are managed by
2022-11-08T23:11:26.14263Z	npm WARN config     [`cacache`](http://npm.im/cacache).
2022-11-08T23:11:26.154628Z	
2022-11-08T23:11:26.154988Z	> hyper-recent@1.0.0 build:data
2022-11-08T23:11:26.155123Z	> cd ./scripts && ./search.sh && ./recommendations.sh
2022-11-08T23:11:26.15525Z	
2022-11-08T23:11:26.667362Z	Fetching from biorxiv between 2022-10-08 and 2022-11-08
2022-11-08T23:14:13.102351Z	numPapersRawBiorxiv: 
2022-11-08T23:14:13.103282Z	Fetching from medrxiv between 2022-10-08 and 2022-11-08
2022-11-08T23:14:28.356771Z	numPapersRawMedrxiv: 
2022-11-08T23:14:28.357284Z	Combining results...
2022-11-08T23:14:29.028963Z	jq - commandline JSON processor [version 1.5-1-a5b5cbe]
2022-11-08T23:14:29.029259Z	Usage: jq [options] <jq filter> [file...]
2022-11-08T23:14:29.02938Z	
2022-11-08T23:14:29.029476Z		jq is a tool for processing JSON inputs, applying the
2022-11-08T23:14:29.029575Z		given filter to its JSON text inputs and producing the
2022-11-08T23:14:29.029702Z		filter's results as JSON on standard output.
2022-11-08T23:14:29.029962Z		The simplest filter is ., which is the identity filter,
2022-11-08T23:14:29.030109Z		copying jq's input to its output unmodified (except for
2022-11-08T23:14:29.030202Z		formatting).
2022-11-08T23:14:29.030299Z		For more advanced filters see the jq(1) manpage ("man jq")
2022-11-08T23:14:29.030394Z		and/or https://stedolan.github.io/jq
2022-11-08T23:14:29.030489Z	
2022-11-08T23:14:29.030579Z		Some of the options include:
2022-11-08T23:14:29.030672Z		 -c		compact instead of pretty-printed output;
2022-11-08T23:14:29.030761Z		 -n		use `null` as the single input value;
2022-11-08T23:14:29.030892Z		 -e		set the exit status code based on the output;
2022-11-08T23:14:29.030995Z		 -s		read (slurp) all inputs into an array; apply filter to it;
2022-11-08T23:14:29.031107Z		 -r		output raw strings, not JSON texts;
2022-11-08T23:14:29.031203Z		 -R		read raw strings, not JSON texts;
2022-11-08T23:14:29.031302Z		 -C		colorize JSON;
2022-11-08T23:14:29.031392Z		 -M		monochrome (don't colorize JSON);
2022-11-08T23:14:29.031483Z		 -S		sort keys of objects on output;
2022-11-08T23:14:29.031573Z		 --tab	use tabs for indentation;
2022-11-08T23:14:29.031665Z		 --arg a v	set variable $a to value <v>;
2022-11-08T23:14:29.031757Z		 --argjson a v	set variable $a to JSON value <v>;
2022-11-08T23:14:29.031858Z		 --slurpfile a f	set variable $a to an array of JSON texts read from <f>;
2022-11-08T23:14:29.03195Z		See the manpage for more options.
2022-11-08T23:14:30.792735Z	Searching for alzheimers-disease
2022-11-08T23:14:30.952441Z	undefined:1
2022-11-08T23:14:30.95274Z	
2022-11-08T23:14:30.952882Z	
2022-11-08T23:14:30.953031Z	SyntaxError: Unexpected end of JSON input
2022-11-08T23:14:30.95316Z	    at JSON.parse (<anonymous>)
2022-11-08T23:14:30.953291Z	    at getInput (file:///opt/buildhome/repo/src/cli.js:67:17)
2022-11-08T23:14:30.953396Z	    at async Command.search (file:///opt/buildhome/repo/src/cli.js:23:20)
2022-11-08T23:14:30.953501Z	    at async Command.parseAsync (/opt/buildhome/repo/node_modules/commander/lib/command.js:917:5)
2022-11-08T23:14:30.953605Z	    at async main (file:///opt/buildhome/repo/src/cli.js:103:3)
2022-11-08T23:14:30.970202Z	Found  hits
2022-11-08T23:14:30.989054Z	jq - commandline JSON processor [version 1.5-1-a5b5cbe]
2022-11-08T23:14:30.98945Z	Usage: jq [options] <jq filter> [file...]
2022-11-08T23:14:30.989592Z	
2022-11-08T23:14:30.98969Z		jq is a tool for processing JSON inputs, applying the
2022-11-08T23:14:30.989787Z		given filter to its JSON text inputs and producing the
2022-11-08T23:14:30.989877Z		filter's results as JSON on standard output.
2022-11-08T23:14:30.989978Z		The simplest filter is ., which is the identity filter,
2022-11-08T23:14:30.990143Z		copying jq's input to its output unmodified (except for
2022-11-08T23:14:30.990239Z		formatting).
2022-11-08T23:14:30.99033Z		For more advanced filters see the jq(1) manpage ("man jq")
2022-11-08T23:14:30.990423Z		and/or https://stedolan.github.io/jq
2022-11-08T23:14:30.990513Z	
2022-11-08T23:14:30.990617Z		Some of the options include:
2022-11-08T23:14:30.990732Z		 -c		compact instead of pretty-printed output;
2022-11-08T23:14:30.990827Z		 -n		use `null` as the single input value;
2022-11-08T23:14:30.990921Z		 -e		set the exit status code based on the output;
2022-11-08T23:14:30.991046Z		 -s		read (slurp) all inputs into an array; apply filter to it;
2022-11-08T23:14:30.991146Z		 -r		output raw strings, not JSON texts;
2022-11-08T23:14:30.991236Z		 -R		read raw strings, not JSON texts;
2022-11-08T23:14:30.991325Z		 -C		colorize JSON;
2022-11-08T23:14:30.991419Z		 -M		monochrome (don't colorize JSON);
2022-11-08T23:14:30.99151Z		 -S		sort keys of objects on output;
2022-11-08T23:14:30.991601Z		 --tab	use tabs for indentation;
2022-11-08T23:14:30.991692Z		 --arg a v	set variable $a to value <v>;
2022-11-08T23:14:30.991794Z		 --argjson a v	set variable $a to JSON value <v>;
2022-11-08T23:14:30.99189Z		 --slurpfile a f	set variable $a to an array of JSON texts read from <f>;
2022-11-08T23:14:30.991983Z		See the manpage for more options.
2022-11-08T23:14:30.998576Z	ERROR: "build:data" exited with 2.
2022-11-08T23:14:31.013194Z	Failed: build command exited with code: 1
2022-11-08T23:14:31.961925Z	Failed: an internal error occurred
```

**Comment by jvwong** [comment]
Maybe I need to make sure this works on linux.

**Comment by jvwong** [comment]
Can reproduce error on Ubuntu 16.04.7 LTS, node 16.16, jq-1.5-1-a5b5cbe ...

**Pull request merged**
